### PR TITLE
Bumped httpserver to 0.18.2 for release

### PR DESCRIPTION
**Pull request by brooksmtownsend**
Releasing https://github.com/wasmCloud/capability-providers/pull/240

### CODE REVIEW

**Comment by connorsmith256** [comment]
Is there urgency here, or can we wait for https://github.com/wasmCloud/capability-providers/pull/241 ?

**Comment by brooksmtownsend** [comment]
@connorsmith256 No urgency, we can leave this one until that merges or just hold on releasing the tag, either way works

**Review by connorsmith256 — APPROVED** [review]
I'm good to merge, was just wondering if you were trying to also tag/release

**Comment by brooksmtownsend** [comment]
Should merge after #243

**Pull request merged**
