### PR TITLE
Http-server & Redis 0.15.0 Updates

### PR DESCRIPTION
**Pull request by brooksmtownsend**
Updates `http-server` provider and `redis` provider to 0.15.0 compliance by using generated data types from `actor-interfaces` and using the `wasmcloud:httpserver` and `wasmcloud:keyvalue` capability contract IDs, respectively. 

I have not addressed all concerns from #12, so I'm creating a Draft PR for now to check in my code. @autodidaddict I will reach out to you next week to make sure I know how to address the rest of the concerns there so I can convert this PR.

### CODE REVIEW

**Comment by brooksmtownsend** [comment]
Failing due to actor-interfaces relative dependency

**Comment by brooksmtownsend** [comment]
@autodidaddict I believe I've addressed the concerns in #12, however there are still some dependencies from `wascc_codec` that are not present in `actor_core`, this is what I'm using it for in redis for example:
```
#[macro_use]
extern crate wascc_codec as codec;
use codec::capabilities::{
    CapabilityDescriptor, CapabilityProvider, Dispatcher, NullDispatcher, OperationDirection,
    OP_GET_CAPABILITY_DESCRIPTOR,
};
use codec::core::{OP_BIND_ACTOR, OP_HEALTH_REQUEST, OP_REMOVE_ACTOR}
```

Would appreciate a second set of eyes if this is correct, or if they should be added to actor-core

**Comment by autodidaddict** [comment]
wascc-codec is not being removed. It is required for all capability providers.

**Comment by autodidaddict** [comment]
Also @brooksmtownsend capability providers should no longer respond to the "get descriptor" operation, as the wasmCloud host runtime no longer sends that message

**Comment by brooksmtownsend** [comment]
@autodidaddict So for `0.15.0` compliance for these two providers we'll just want to remove the Descriptor related functionality, and we're good to go? Do we want to put some of the operation constants like `OP_BIND_ACTOR` into `actor-core`?

**Review by autodidaddict — APPROVED** [review]

**Pull request merged**
